<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Henrik Bengtsson" />


<title>port4me: Get the Same, Personal, Free TCP Port over and over</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>
<script>// Hide empty <a> tag within highlighted CodeBlock for screen reader accessibility (see https://github.com/jgm/pandoc/issues/6352#issuecomment-626106786) -->
// v0.0.1
// Written by JooYoung Seo (jooyoung@psu.edu) and Atsushi Yasumoto on June 1st, 2020.

document.addEventListener('DOMContentLoaded', function() {
  const codeList = document.getElementsByClassName("sourceCode");
  for (var i = 0; i < codeList.length; i++) {
    var linkList = codeList[i].getElementsByTagName('a');
    for (var j = 0; j < linkList.length; j++) {
      if (linkList[j].innerHTML === "") {
        linkList[j].setAttribute('aria-hidden', 'true');
      }
    }
  }
});
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">port4me: Get the Same, Personal, Free TCP Port over and over</h1>
<h4 class="author">Henrik Bengtsson</h4>



<p>The <strong>port4me</strong> tool:</p>
<ul>
<li><p>finds a free TCP port in [1024,65535] that the user can open</p></li>
<li><p>is designed to work in multi-user environments</p></li>
<li><p>gives different users, different ports</p></li>
<li><p>gives the user the same port over time with high probability</p></li>
<li><p>gives different ports for different software tools</p></li>
<li><p>requires no configuration</p></li>
<li><p>can be reproduced perfectly on all operating systems and in all common programming languages</p></li>
</ul>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>There are many tools to identify a free TCP port, where most of them return a random port. Although it works technically, it might add a fair bit of friction if a new random port number has to be entered by the user each time they need to use a specific tool.</p>
<p>In contrast, <strong>port4me</strong> attempts, with high probability, to provide the user with the same port each time, even when used on different days. It achieves this by scanning the same deterministic, pseudo-random sequence of ports and return the first free port detected. Each user gets their own random port sequence, lowering the risk for any two users to request the same port. The randomness is initiated with a random seed that is a function of the user’s name (<code>USER</code>), and, optionally, the name of the software where we use the port.</p>
<p>The <strong>port4me</strong> algorithm can be implemented in most known programming languages, producing perfectly reproducible sequencing regardless of implementation language.</p>
</div>
<div id="a-quick-introduction" class="section level2">
<h2>A quick introduction</h2>
<p>Assuming we’re logged in as user <code>alice</code> and calls <code>port4me::port4me()</code> without arguments gives us a free port:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true"></a><span class="kw">Sys.info</span>()[[<span class="st">&quot;user&quot;</span>]]</span></code></pre></div>
<pre class="plain"><code>## [1] &quot;alice&quot;</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>()</span></code></pre></div>
<pre><code>## [1] 30845</code></pre>
<p>As we will see later, each user on the system is likely to get their own unique port. Because of this, it can be used to specifying a port that some tool should use, e.g.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true"></a>shiny<span class="op">::</span><span class="kw">runApp</span>(<span class="dt">port =</span> port4me<span class="op">::</span><span class="kw">port4me</span>())</span></code></pre></div>
<p>As long as this port is available, <code>alice</code> will always get the same port across R sessions and over time. For example, if they return next week and retry, it’s likely they still get:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>()</span></code></pre></div>
<pre><code>## [1] 30845</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>()</span></code></pre></div>
<pre><code>## [1] 30845</code></pre>
<p>However, if port 30845 is already occupied, the next port in the pseudo-random sequence is considered, e.g.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>()</span></code></pre></div>
<pre><code>## [1] 19654</code></pre>
<p>To see the first five ports scanned, run:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="dt">list =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 30845 19654 32310 63992 15273</code></pre>
</div>
<div id="user-specific-deterministic-pseudo-random-port-sequence" class="section level2">
<h2>User-specific, deterministic, pseudo-random port sequence</h2>
<p>This random sequence is initiated by a random seed that can be set via the hashcode of a seed string. By default, it is based on the name of the current user (e.g. environment variable <code>$USER</code>). For example, when user <code>bob</code> uses the <code>port4me</code> tool, they see another set of ports being scanned:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true"></a><span class="kw">Sys.info</span>()[[<span class="st">&quot;user&quot;</span>]]</span></code></pre></div>
<pre class="plain"><code>## [1] &quot;bob&quot;</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="dt">list =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 30845 19654 32310 63992 15273</code></pre>
<p>For testing and demonstration purposes, one can emulate another user by specifying argument <code>user</code>, e.g.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true"></a><span class="kw">Sys.info</span>()[[<span class="st">&quot;user&quot;</span>]]</span></code></pre></div>
<pre class="plain"><code>## [1] &quot;alice&quot;</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>()</span></code></pre></div>
<pre><code>## [1] 30845</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="dt">user =</span> <span class="st">&quot;bob&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 54242</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="dt">user =</span> <span class="st">&quot;carol&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 34307</code></pre>
</div>
<div id="different-ports-for-different-software-tools" class="section level2">
<h2>Different ports for different software tools</h2>
<p>Sometimes a user would like to use two, or more, ports at the same time, e.g. two ports for two different Shiny apps. In such case, they can specify argument <code>tool</code>, which results in a port sequence that is unique to both the user and the tool. For example,</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>()</span></code></pre></div>
<pre><code>## [1] 30845</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="st">&quot;myapp&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 55578</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="st">&quot;demo&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 32273</code></pre>
<p>This allows us to do:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true"></a>shiny<span class="op">::</span><span class="kw">runApp</span>(<span class="dt">appDir =</span> <span class="st">&quot;myapp&quot;</span>, <span class="dt">port =</span> port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="st">&quot;myapp&quot;</span>))</span></code></pre></div>
<p>and</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true"></a>shiny<span class="op">::</span><span class="kw">runApp</span>(<span class="dt">appDir =</span> <span class="st">&quot;demo&quot;</span>, <span class="dt">port =</span> port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="st">&quot;demo&quot;</span>))</span></code></pre></div>
</div>
<div id="avoid-using-ports-commonly-used-elsewhere" class="section level2">
<h2>Avoid using ports commonly used elsewhere</h2>
<p>Since there is a limited set of ports available (1024-65535), there is always a risk that another process occupies any given port. The more users there are on the same machine, the higher the risk is for this to happen. If a user is unlucky, they might experience this frequently. For example, <code>alice</code> might find that the first port (30845) works only one out 10 times, whereas the second port (19654) works 99 out 100 times, and the third one (32310) works so and so. If so, they might choose to exclude the “flaky” ports by specifying them as a comma-separated values via argument <code>exclude</code>, e.g.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="dt">exclude =</span> <span class="kw">c</span>(<span class="dv">30845</span>, <span class="dv">32310</span>))</span></code></pre></div>
<pre class="plain"><code>[1] 20678</code></pre>
<p>An alternative to specify them via a command-line option, is to specify them via environment variable <code>PORT4ME_EXCLUDE</code>, e.g.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true"></a>{alice}<span class="op">$</span><span class="st"> </span>PORT4ME_EXCLUDE=<span class="dv">30845</span>,<span class="dv">32310</span> R</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true"></a>...</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true"></a><span class="op">&gt;</span><span class="st"> </span>port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="dt">exclude =</span> <span class="kw">c</span>(<span class="dv">30845</span>, <span class="dv">32310</span>))</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true"></a>[<span class="dv">1</span>] <span class="dv">20678</span></span></code></pre></div>
<p>To set this permanently, append:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode sh"><code class="sourceCode bash"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true"></a><span class="co">## port4me customization</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true"></a><span class="co">## https://github.com/HenrikBengtsson/port4me</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true"></a><span class="va">PORT4ME_EXCLUDE=</span>30845,32310</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true"></a><span class="bu">export</span> <span class="va">PORT4ME_EXCLUDE</span></span></code></pre></div>
<p>to the shell startup script, e.g. <code>~/.bashrc</code>. Alternatively, it can be set specifically for R in <code>~/.Renviron</code> as:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode sh"><code class="sourceCode bash"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true"></a><span class="co">## port4me customization</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true"></a><span class="co">## https://github.com/HenrikBengtsson/port4me</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true"></a><span class="va">PORT4ME_EXCLUDE=</span>30845,32310</span></code></pre></div>
<p>This increases the chances for the user to end up with the same port over time, which is convenient, because then they can reuse the same call, which is available in the command-line history, each time without having to change the port parameter.</p>
<p>The environment variable <code>PORT4ME_EXCLUDE</code> is intended to be used by the individual user. To specify a set of ports to be excluded regardless of user, set <code>PORT4ME_EXCLUDE_SITE</code>. For example, the systems administrator, can choose to exclude an additional set of ports by adding the following to file <code>/etc/profile.d/port4me.sh</code>:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode sh"><code class="sourceCode bash"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true"></a><span class="co">## port4me: always exclude commonly used ports</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true"></a><span class="co">## https://github.com/HenrikBengtsson/port4me</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true"></a><span class="va">PORT4ME_EXCLUDE_SITE=</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true"></a><span class="co">## MySQL</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true"></a><span class="va">PORT4ME_EXCLUDE_SITE=$PORT4ME_EXCLUDE_SITE</span>,3306</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true"></a></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true"></a><span class="co">## ZeroMQ</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true"></a><span class="va">PORT4ME_EXCLUDE_SITE=$PORT4ME_EXCLUDE_SITE</span>,5670</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true"></a><span class="co">## Redis</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true"></a><span class="va">PORT4ME_EXCLUDE_SITE=$PORT4ME_EXCLUDE_SITE</span>,6379</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true"></a></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true"></a><span class="co">## Jupyter</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true"></a><span class="va">PORT4ME_EXCLUDE_SITE=$PORT4ME_EXCLUDE_SITE</span>,8888</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true"></a></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true"></a><span class="bu">export</span> <span class="va">PORT4ME_EXCLUDE_SITE</span></span></code></pre></div>
<p>In addition to ports excluded via above mechanisms, <strong>port4me</strong> excludes ports that are considered unsafe by the Chrome and Firefox web browsers. This behavior can be controlled by environment variable <code>PORT4ME_EXCLUDE_UNSAFE</code>, which defaults to <code>{chrome},{firefox}</code>. Token <code>{chrome}</code> expands to the value of <code>PORT4ME_EXCLUDE_UNSAFE_CHROME</code>, which defaults to <a href="https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/net/base/port_util.cc">the set of ports that Chrome blocks</a> and <code>{firefox}</code> expands to to the value of <code>PORT4ME_EXCLUDE_UNSAFE_FIREFOX</code>, which defaults to <a href="https://www-archive.mozilla.org/projects/netlib/portbanning#portlist">the set of ports that Firefox blocks</a>.</p>
<p>Analogously to excluding a set of ports, one can limit the range of ports to be scanned by specifying command-line argument <code>include</code>, e.g.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="dt">include =</span> <span class="kw">c</span>(<span class="dv">2000</span><span class="op">:</span><span class="dv">2123</span>, <span class="dv">4321</span>, <span class="dv">10000</span><span class="op">:</span><span class="dv">10999</span>))</span></code></pre></div>
<pre><code>## [1] 10451</code></pre>
<p>where the default corresponds to <code>include = 1024:65535</code>. Analogously to <code>exclude</code>, <code>include</code> can be specified via environment variables <code>PORT4ME_INCLUDE</code> and <code>PORT4ME_INCLUDE_SITE</code>.</p>
</div>
<div id="scan-a-predefined-set-of-ports-before-pseudo-random-ones" class="section level2">
<h2>Scan a predefined set of ports before pseudo-random ones</h2>
<p>In addition to scanning the user-specific, pseudo-random port sequence for a free port, it is possible to also consider a predefined set of ports prior to the random ones by specifying command-line argument <code>prepend</code>, e.g.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="dt">prepend =</span> <span class="kw">c</span>(<span class="dv">4321</span>, <span class="dv">11001</span>), <span class="dt">list =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1]  4321 11001 30845 19654 32310</code></pre>
<p>An alternative to specify them via a command-line option, is to specify them via environment variable <code>PORT4ME_PREPEND</code>, e.g.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true"></a>{alice}<span class="op">$</span><span class="st"> </span>PORT4ME_PREPEND=<span class="dv">4321</span>,<span class="dv">11001</span> R</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true"></a>...</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true"></a><span class="op">&gt;</span><span class="st"> </span>port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="dt">list =</span> <span class="dv">5</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true"></a>[<span class="dv">1</span>]  <span class="dv">4321</span> <span class="dv">11001</span> <span class="dv">30845</span> <span class="dv">19654</span> <span class="dv">32310</span></span></code></pre></div>
<p>The environment variable <code>PORT4ME_PREPEND</code> is intended to be used by the individual user. To specify a set of ports to be prepended regardless of user, set <code>PORT4ME_PREPEND_SITE</code>.</p>
</div>
<div id="installation" class="section level2">
<h2>Installation</h2>
<p>To install the R <strong>portme</strong> package, do:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true"></a><span class="kw">install.packages</span>(<span class="st">&quot;port4me&quot;</span>)</span></code></pre></div>
<p>To install the development version, do:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true"></a>remotes<span class="op">::</span><span class="kw">install_github</span>(<span class="st">&quot;HenrikBengtsson/port4me&quot;</span>, <span class="dt">subdir =</span> <span class="st">&quot;r&quot;</span>)</span></code></pre></div>
<p>To try it out, call:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true"></a>port4me<span class="op">::</span><span class="kw">port4me</span>(<span class="st">&quot;jupyter-notebook&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 29525</code></pre>
<p>or</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode sh"><code class="sourceCode bash"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true"></a><span class="ex">Rscript</span> -e <span class="st">&#39;cat(port4me::port4me(&quot;jupyter-notebook&quot;))&#39;</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true"></a><span class="ex">29525</span></span></code></pre></div>
</div>
<div id="the-port4me-algorithm" class="section level2">
<h2>The port4me Algorithm</h2>
<div id="requirements" class="section level3">
<h3>Requirements</h3>
<ul>
<li><p>It should be possible to implement the algorithm using 32-bit <em>unsigned</em> integer arithmetic. One must not assume that the largest represented integer can exceed <span class="math inline">\(2^{32} - 1\)</span>.</p></li>
<li><p>The pseudo-randomized port sequence should sample ports uniformly over <span class="math inline">\([1024, 65535]\)</span>.</p></li>
<li><p>At a minimum, it should be possible to implement the algorithm in vanilla Sh*, Csh, Bash, C, C++, Fortran, Lua, Python, R, and Ruby, with <em>no</em> need for add-on packages beyond what is available from their core distribution. (*) Shells that do not support integer arithmetic may use tools such as <code>expr</code>, <code>dc</code>, <code>bc</code>, and <code>awk</code> for these calculations.</p></li>
<li><p>All programming languages should produce the exact same pseudo-random port sequences given the same random seed.</p></li>
<li><p>The implementations should be written such that they work also when sourced, or copy’and’pasted into source code elsewhere, e.g. in R and Python scripts.</p></li>
<li><p>The identified, free port should be outputted to the standard output (stdout) as digits only, without any prefix or suffix symbols.</p></li>
<li><p>The user should be able to exclude a pre-defined set of ports by specifying environment variable <code>PORT4ME_EXCLUDE</code>, e.g. <code>PORT4ME_EXCLUDE=8080,4321</code>.</p></li>
<li><p>The system administrator should be able to specify a pre-defined set of ports to be excluded by specifying environment variable <code>PORT4ME_EXCLUDE_SITE</code>, e.g. <code>PORT4ME_EXCLUDE_SITE=8080,4321</code>. This works complementary to <code>PORT4ME_EXCLUDE</code>.</p></li>
<li><p>The user should be able to skip a certain number of random ports at their will by specifying environment variable <code>PORT4ME_SKIP</code>, e.g. <code>PORT4ME_SKIP=5</code>. The default is to not skip, which corresponds to <code>PORT4ME_SKIP=0</code>. Skipping should apply <em>after</em> ports are excluding by <code>PORT4ME_EXCLUDE</code> and <code>PORT4ME_EXCLUDE_SITE</code>.</p></li>
<li><p>New implementations should perfectly reproduce the port sequences produced by already existing implementations.</p></li>
</ul>
</div>
<div id="design" class="section level3">
<h3>Design</h3>
<ul>
<li><p>A <em><a href="https://en.wikipedia.org/wiki/Linear_congruential_generator">Linear congruential generator (LCG)</a></em> will be used to generate the pseudo-random port sequence</p>
<ul>
<li><p>the next seed, <span class="math inline">\(s_{n+1}\)</span> is calculated based on the current seed <span class="math inline">\(s_n\)</span> and parameters <span class="math inline">\(a, c, m &gt; 1\)</span> as <span class="math inline">\(s_{n+1} = (a * s_{n} + c) \% m\)</span></p></li>
<li><p>the LCG algorithm must not assume that the current LCG seed is within <span class="math inline">\([0,m-1]\)</span>, i.e. it should apply modulo <span class="math inline">\(m\)</span> on the seed first to avoid integer overflow</p></li>
<li><p>the LCG algorithm may produce the same output seed as input seed, which may happen when the seed is <span class="math inline">\(s_n = m - (a - c)\)</span>. To avoid this resulting in a constant LCG stream, increment the seed by one and recalculate whenever this happens</p></li>
<li><p>LCG parameters should be <span class="math inline">\(m = 2^{16} + 1\)</span>, <span class="math inline">\(a = 75\)</span>, and <span class="math inline">\(c = 74\)</span> (“ZX81”)</p>
<ul>
<li><p>this requires only 32-bit integer arithmetic, because <span class="math inline">\(m &lt; 2^{32}\)</span></p></li>
<li><p>if the initial seed is <span class="math inline">\(s_0 = m - (a - c)\)</span>, which here is <span class="math inline">\(m - 1 = 2^{16}\)</span>, then the next LCG seed will be the same, which is then handled by the above increment-by-one workaround</p></li>
</ul></li>
</ul></li>
<li><p>A <em>32-bit integer string hashcode</em> will be used to generate an integer in <span class="math inline">\([0,2^{32}-1]\)</span> from an ASCII string with any number of characters. The hashcode algorithm is based on the Java hashcode algorithm, but uses unsigned 32-bit integers in <span class="math inline">\([0,2^{32}-1]\)</span>, instead of signed ones in <span class="math inline">\([-2^{31},2^{31}-1]\)</span></p></li>
<li><p>The string hashcode is used as the initial LCG seed:</p>
<ul>
<li><p>the LCG seed should be in <span class="math inline">\([0,m-1]\)</span></p></li>
<li><p>given hashcode <span class="math inline">\(h\)</span>, we can generate the initial LCG seed as <span class="math inline">\(h\)</span> modulo <span class="math inline">\(m\)</span></p></li>
</ul></li>
</ul>
</div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
